#! /bin/sh

ps aux | grep ./switch | grep -v grep | cut -d " " -f 2 | xargs kill
ps aux | grep ./testbed | grep -v grep | cut -d " " -f 2 | xargs kill
ps aux | grep ./listenserver.out | grep -v grep | cut -d " " -f 2 | xargs kill
ps aux | grep ./node.out | grep -v grep | cut -d " " -f 2 | xargs kill

